name: github actions for airflow dags

on:
  push:
    paths:
      - 'airflow/dags/**'
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up .env
      run: echo "${{ secrets.ENV }}" > .env

    - name: Build and Run Docker Compose
      run: |
        docker-compose-test up -d
        
    - name: Test with pytest
      run: |
        pip install pytest
        pytest airflow/tests
